### PR TITLE
document remaining function

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by fulldecent** [comment]
Bump. Ready to pull.

**Comment by fulldecent** [comment]
@ArthurGuibert

To be clear, are you still accepting contributions to this project?? If so is this PR in scope to be merged?

**Comment by ArthurGuibert** [comment]
I'm still accepting PR. This PR is still lacking a bit of context though. I would appreciate a short description in the commit message that's it 🙂

**Comment by fulldecent** [comment]
You got it. New PR at https://github.com/ArthurGuibert/FSLineChart/pull/42

**Pull request closed without merging**
